name: 'Minify JS assets'
description: 'Does some minifying'

inputs:
  directory:
    description: "Files to minify"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: "box"
  color: "green"
